default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8

# local PC
development:
  adapter: mysql2
  database: agri_record
  host: localhost
  username: testuser
  password: agrirecord
  encoding: utf8
  socket: '/Applications/MAMP/tmp/mysql/mysql.sock'

# production server用
production:
  <<: *default
  database: agri_record
  host: 133.242.141.56
  username: agri_test
  password: kansatunet
  socket: '/var/lib/mysql/mysql.sock'
